- apps/web/src/app/fiches-pratiques/page.tsx
- apps/web/src/app/fiches-pratiques/qu-est-ce-que-l-autisme/head.tsx
- apps/web/src/app/fiches-pratiques/qu-est-ce-que-l-autisme/page.tsx
- apps/web/src/app/page.tsx
- apps/web/src/components/layouts/BasicLayout.tsx
- apps/web/src/design-system/base/Callout.module.css
- apps/web/src/design-system/base/CollapsedSection.module.css
- apps/web/src/design-system/base/CollapsedSection.tsx
- apps/web/src/design-system/base/CollapsedSectionGroup.module.css
- apps/web/src/design-system/base/CollapsedSectionGroup.tsx
- apps/web/src/design-system/base/MainNav.tsx
- apps/web/src/design-system/base/SideMenu.tsx
- apps/web/src/design-system/index.ts
- apps/web/src/styles/global.css
- package.json
> feat: add static fiche pratique

- .releaserc.js
Closes nothing
- Corriger la config de release rc pour les futurs tags sur la branch `main`
> chore: change releaserc config

- apps/web/src/components/base/BreadcrumbDynamic.module.css
- apps/web/src/components/base/BreadcrumbDynamic.tsx
- apps/web/src/design-system/base/Breadcrumb.tsx
> fix: better Breadcrumb position

- apps/strapi/index.d.ts
- apps/strapi/package.json
- apps/strapi/src/api/home-hero/content-types/home-hero/schema.json
- apps/strapi/src/api/question/content-types/question/schema.json
- apps/strapi/src/api/question/controllers/question.ts
- apps/strapi/src/api/question/routes/question.ts
- apps/strapi/src/api/question/services/question.ts
- apps/strapi/src/components/parcours-diag/answer.json
- apps/strapi/src/components/parcours-diag/reponse.json
- apps/strapi/src/components/parcours-diag/sub-answer.json
- apps/web/src/services/strapi.ts
- mindmap.md
- yarn.lock
Closes nothing
- Prepare "Parcours de diagnostic" feature
- Clean strapi models
> chore: mindmap strategy

- apps/web/package.json
- apps/web/src/app/healthz/page.tsx
- apps/web/src/app/je-donne-mon-avis/head.tsx
- apps/web/src/app/je-donne-mon-avis/page.tsx
- apps/web/src/app/mentions-legales/page.tsx
- apps/web/src/app/mon-parcours/parent-personne-aidante/page.tsx
- apps/web/src/app/page.tsx
- apps/web/src/components/base/FormGroupInput.tsx
- apps/web/src/components/base/FormGroupSelect.tsx
- apps/web/src/components/base/FormGroupTextarea.tsx
- apps/web/src/components/layouts/BasicLayout.tsx
- apps/web/src/design-system/base/Fieldset.tsx
- apps/web/src/design-system/base/FormInput.tsx
- apps/web/src/design-system/base/FormTextarea.tsx
- apps/web/src/design-system/index.ts
- yarn.lock
> feat: add feedback page

- apps/web/src/app/modeles-de-courrier/page.tsx
- apps/web/src/app/page.tsx
- apps/web/src/design-system/base/DownloadLink.tsx
- apps/web/src/design-system/index.ts
> feat: add download page

- apps/web/src/app/annuaire/head.tsx
- apps/web/src/app/annuaire/page.tsx
- apps/web/src/app/glossaire/head.tsx
- apps/web/src/app/glossaire/page.tsx
- apps/web/src/app/modeles-de-courrier/head.tsx
- apps/web/src/common/config/index.ts
- apps/web/src/components/layouts/BasicLayout.tsx
> fix: wording

- .github/workflows/testify.yml
> fix: testing

- apps/web/src/app/la-maison-de-l-autisme/page.tsx
- apps/web/src/app/politique-de-confidentialite/page.tsx
> fix: clean dummy

- apps/web/src/app/annuaire/page.tsx
- apps/web/src/app/glossaire/page.tsx
- apps/web/src/app/mentions-legales/page.tsx
- apps/web/src/app/modeles-de-courrier/page.tsx
- apps/web/src/app/politique-de-confidentialite/page.tsx
- apps/web/src/components/base/client/Header.tsx
- apps/web/src/components/layouts/BasicLayout.tsx
> feat: update wording

- apps/web/src/app/mon-parcours/Tiles.tsx
- apps/web/src/app/mon-parcours/parent-personne-aidante/page.tsx
- apps/web/src/app/mon-parcours/personne-autiste/page.tsx
- apps/web/src/app/mon-parcours/professionnel-de-sante/page.tsx
- apps/web/src/app/page.tsx
> feat: add wording and links

- apps/web/src/app/glossaire/page.tsx
- apps/web/src/app/la-maison-de-l-autisme/page.tsx
- apps/web/src/app/mentions-legales/page.tsx
- apps/web/src/app/mon-parcours/page.tsx
- apps/web/src/app/mon-parcours/personne-autiste/page.tsx
- apps/web/src/app/mon-parcours/professionnel-de-sante/page.tsx
> feat: update content

- apps/web/src/app/mon-parcours/personne-autiste/page.tsx
Closes #92
Permet de résoudre les soucis d'URL de la page `mon-parcours/personne-autiste`
> fix: dummy url

- apps/web/src/app/plan-du-site/head.tsx
- apps/web/src/app/plan-du-site/page.tsx
- apps/web/src/components/base/client/Header.tsx
- apps/web/src/components/layouts/BasicLayout.tsx
- apps/web/src/design-system/base/client/MainNav.tsx
Closes #95 #40 
- [Comportement pas ergonomique menu hamburger](https://github.com/SocialGouv/mda/issues/95)
- Ajout de la page plan du site
> feat: add sitemap page

- apps/strapi/config/sync/admin-role.strapi-super-admin.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##accueil.accueil.json
- apps/strapi/src/api/accueil/content-types/accueil/schema.json
- apps/strapi/src/utils/seed/accueil.json
- apps/web/next.config.js
- apps/web/src/app/(main)/page.tsx
- apps/web/src/services/strapiApiTypes.ts
- packages/strapi-types/index.d.ts
Closes #107 
Cette PR rend disponible l'ajout d'une image sur la page d'accueil dans strapi et un fallback sur l'image prévue dans le ticket si cette image n'est pas présente dans l'admin
> feat(home): Add dynamic image

- apps/web/src/common/config/csp.config.js
Closes #164
Cette PR a pour but d'autoriser les vidéos youtube via des iframes en rajoutant le domaine aux csp
> featvideos): Allow embedded youtube videos

- apps/web/src/app/(main)/layout.tsx
- apps/web/src/app/(main)/politique-de-confidentialite/page.tsx
Mise en place de TarteAuCitron
> feat: add TarteAuCitron

- .vscode/settings.json
- apps/strapi/config/sync/admin-role.strapi-super-admin.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##event.event.json
- apps/strapi/config/sync/user-role.public.json
- apps/strapi/src/api/event/content-types/event/schema.json
- apps/strapi/src/api/event/controllers/event.ts
- apps/strapi/src/api/event/routes/event.ts
- apps/strapi/src/api/event/services/event.ts
- apps/strapi/src/api/maison-de-l-autisme/content-types/maison-de-l-autisme/schema.json
- apps/strapi/src/api/maison-de-l-autisme/controllers/maison-de-l-autisme.ts
- apps/strapi/src/api/maison-de-l-autisme/routes/01-custom-routes.ts
- apps/strapi/src/api/maison-de-l-autisme/routes/maison-de-l-autisme.ts
- apps/strapi/src/api/maison-de-l-autisme/services/maison-de-l-autisme.ts
- apps/strapi/src/extensions/meilisearch/strapi-server.ts
- apps/strapi/src/utils/ctxParamsHelper.ts
- apps/web/src/app/(main)/la-maison-de-l-autisme/page.tsx
- apps/web/src/app/(main)/page.tsx
- apps/web/src/design-system/base/LinkGroup.tsx
- apps/web/src/services/strapi.ts
- apps/web/src/styles/global.css
- packages/strapi-types/index.d.ts
- packages/strapi-types/strapi.d.ts
Closes #122 
Module de création d'évènements de la maison de l'autisme
> feat(events): MDA events

- apps/web/src/components/utils/Markdown.tsx
Corrige la gestion du responsive des iframes et des images provenant de Strapi. Ajoute un zoom automatique de 150% aux fichiers PDF visualisés dans une iframe.
> feat: add responsive iframe and img in strapi content

- .kontinuous/env/prod/values.yaml
- adjust resources for web, strapi, meilisearch
- activate HPA
Closes #x
> adjust-resources

- apps/strapi/config/sync/admin-role.strapi-super-admin.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##accueil.accueil.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##diagnostic.diagnostic.json
- apps/strapi/config/sync/core-store.plugin_meilisearch_meilisearch_indexed_content_types.json
- apps/strapi/config/sync/user-role.public.json
- apps/strapi/src/api/diagnostic/content-types/diagnostic/schema.json
- apps/strapi/src/api/diagnostic/controllers/diagnostic.ts
- apps/strapi/src/api/diagnostic/routes/diagnostic.ts
- apps/strapi/src/api/diagnostic/services/diagnostic.ts
- apps/strapi/src/bootstrap/dev/seed-db.ts
- apps/strapi/src/utils/seed/diagnostic.json
- apps/web/src/app/(main)/mon-diagnostic/head.tsx
- apps/web/src/app/(main)/mon-diagnostic/page.tsx
- apps/web/src/components/base/client/Header.tsx
- packages/strapi-types/strapi.d.ts
Dynamisation de la page Mon diagnostic
> feat: dynamicizing the diagnostic page

- apps/web/src/app/(main)/mon-diagnostic/page.tsx
- apps/web/src/design-system/base/Footer.tsx
- apps/web/src/design-system/base/client/MainNav.tsx
- apps/web/src/styles/global.css
Améliorations d'accessibilité suite aux retours du contre-audit.
> fix: resize textarea only vertically

- apps/strapi/config/sync/admin-role.strapi-super-admin.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_components##common.alerts.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_components##common.inputs.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_components##common.options.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_components##common.selects.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_components##common.textareas.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_components##je-donne-mon-avis.feedback-form.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##je-donne-mon-avis.je-donne-mon-avis.json
- apps/strapi/config/sync/user-role.public.json
- apps/strapi/src/api/je-donne-mon-avis/content-types/je-donne-mon-avis/schema.json
- apps/strapi/src/api/je-donne-mon-avis/controllers/je-donne-mon-avis.ts
- apps/strapi/src/api/je-donne-mon-avis/routes/je-donne-mon-avis.ts
- apps/strapi/src/api/je-donne-mon-avis/services/je-donne-mon-avis.ts
- apps/strapi/src/bootstrap/dev/seed-db.ts
- apps/strapi/src/components/common/alerts.json
- apps/strapi/src/components/common/inputs.json
- apps/strapi/src/components/common/options.json
- apps/strapi/src/components/common/selects.json
- apps/strapi/src/components/common/textareas.json
- apps/strapi/src/components/je-donne-mon-avis/feedback-form.json
- apps/strapi/src/utils/seed/je-donne-mon-avis.json
- apps/web/src/app/(main)/je-donne-mon-avis/FeedbackForm.tsx
- apps/web/src/app/(main)/je-donne-mon-avis/page.tsx
Closes #161
Le texte du formulaire je donne mon avis est complètement dynamisé
> feat(je-donne-mon-avis): dynamisation

- apps/web/src/app/(main)/layout.tsx
- apps/web/src/app/(main)/recherche/SearchResult.tsx
- apps/web/src/app/(main)/recherche/head.tsx
- apps/web/src/app/(main)/recherche/page.tsx
- apps/web/src/components/base/SearchResultsList.tsx
- apps/web/src/components/base/client/Header.tsx
- apps/web/src/services/strapi.ts
- apps/web/src/styles/global.css
> feat: add search page

- apps/web/src/components/utils/client/TarteAuCitronGDPR.tsx
- apps/web/types/tarteaucitronjs.d.ts
Closes #159
La modale tarte au citron ne s'ouvrait plus
> fix(tarteaucitron): modal not opening

- apps/strapi/config/middlewares.ts
Closes #191 
Augmente la taille maximale des fichiers à 512Mb
> feat(uploads): Increase file size to 512Mb

- apps/strapi/config/plugins.ts
Closes #38
Ajout des sections fiches pratiques et etapes de vie dans la recherche
> fix(search): Add sections

- apps/strapi/src/api/glossaire-item/content-types/glossaire-item/schema.json
Closes #199 
Dans strapi quand un champ a un Regex pattern. Il faut le fournir sans les `/`
> fix(glossary): Broken url regex

- apps/web/src/app/(main)/je-donne-mon-avis/FeedbackForm.tsx
> fix: changing the style of the contact page feedback component

- .kontinuous/env/prod/values.yaml
> fix: Revert "fix(prod): Increase memory limit killing pods during upload"

- .kontinuous/env/prod/values.yaml
- web
- move to gouv.fr host
- add ssl certificate
- strapi
- move to gouv.fr host
- add ssl certificate
Closes #x
> feat: prepare move to gouv.fr

- .kontinuous/env/dev/values.yaml
- .kontinuous/env/preprod/values.yaml
- .kontinuous/env/prod/values.yaml
- .kontinuous/values.yaml
Closes nothing
- change `-` to `.` in strapi url for all envs
> fix: adapt strapi url with cert wildcard dns zone

- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##accueil.accueil.json
- apps/strapi/src/api/accueil/content-types/accueil/schema.json
- apps/strapi/src/utils/seed/accueil.json
- apps/web/src/app/(main)/page.tsx
- packages/strapi-types/strapi.d.ts
Closes #232 
Cette PR traite dans l'urgence les retours de la maison de l'autisme
> chore: Adapt home following mda needs

- apps/strapi/package.json
- apps/strapi/src/api/maison-de-l-autisme/controllers/maison-de-l-autisme.ts
- apps/web/package.json
- package.json
- packages/eslint-config/package.json
- packages/strapi-types/package.json
- yarn.lock
Closes dependabot
Cette PR fait taire dependabot
> chore(deps): update dependencies

- apps/strapi/config/plugins.ts
- apps/strapi/config/sync/core-store.plugin_meilisearch_meilisearch_indexed_content_types.json
- apps/strapi/config/sync/core-store.plugin_meilisearch_meilisearch_listened_content_types.json
- apps/web/src/services/strapi.ts
Closes #243 
Cette PR ajoute la page à la search
> feat(modeles-de-courrier): Add to search

- .vscode/settings.json
- apps/web/src/app/(main)/mon-parcours/page.tsx
Cette PR dynamise la partie manquante des parcours
> feat(parcours): Last dynamisation

- apps/strapi/config/sync/admin-role.strapi-super-admin.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_components##common.links.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_components##common.most-viewed-cards.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##footer.footer.json
- apps/strapi/config/sync/user-role.public.json
- apps/strapi/src/api/footer/content-types/footer/schema.json
- apps/strapi/src/api/footer/controllers/footer.ts
- apps/strapi/src/api/footer/routes/footer.ts
- apps/strapi/src/api/footer/services/footer.ts
- apps/strapi/src/bootstrap/dev/seed-db.ts
- apps/strapi/src/components/common/links.json
- apps/strapi/src/utils/seed/footer.json
- packages/strapi-types/strapi.d.ts
> feat: footer strapi api

- apps/web/src/app/(main)/layout.tsx
- apps/web/src/components/utils/Markdown.tsx
- apps/web/src/design-system/base/Footer.tsx
- apps/web/src/styles/global.css
> feat: add dynamic footer

- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##accueil.accueil.json
- apps/strapi/src/api/accueil/content-types/accueil/schema.json
- apps/strapi/src/api/accueil/controllers/accueil.ts
- apps/strapi/src/api/accueil/routes/accueil.ts
- apps/strapi/src/api/accueil/services/accueil.ts
- apps/strapi/src/utils/seed/accueil.json
Closes #213 
Cette PR déprécie l'accueil v1 et le remplace par l'accueil v2. La prochaine supprimera l'accueil v2.
> chore(accueil): Make accueil V1 accueil v2

- apps/web/src/app/(main)/page.tsx
- apps/web/src/services/strapi.ts
Closes TODO
Cette PR permet de typer le résultat d'une méthode de collection avec une autre collection
> chore(types): Better signature for collections methods

- apps/web/src/components/utils/Markdown.tsx
> Fix: iframe video autoplay

- apps/strapi/config/sync/admin-role.strapi-super-admin.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_components##common.icons.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##footer.footer.json
- apps/strapi/src/api/footer/content-types/footer/schema.json
- apps/strapi/src/components/common/icons.json
- apps/strapi/src/utils/seed/footer.json
- apps/web/src/app/(main)/layout.tsx
- packages/strapi-types/strapi.d.ts
Closes #275 
Cette PR ajoute le bandeau réseaux sociaux au footer
> feat(footer): Banner dynamisation

- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_components##common.links.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_components##common.tiles.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_components##fiche-pratique-content.encart.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##etape-de-vie.etape-de-vie.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##fiche-pratique.fiche-pratique.json
- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##parcours.parcours.json
Closes #271 
Cette PR cleane les hints utilisés dans l'admin strapi
> fix(strapi): Admin doc

- apps/web/next.config.js
#x278
Ne pas renvoyer le header sur tous les environnements
> fix(seo): Do not send headers on each environments

- apps/web/src/app/startDsfr.ts
- apps/web/src/components/utils/client/Matomo.tsx
- apps/web/src/design-system/base/client/ConsentBanner.tsx
Cette PR réactive les events matomo à la navigation
> fix(matomo): Track navigation

- .kontinuous/env/prod/templates/www-redirect.yaml
- .kontinuous/env/prod/values.yaml
Ajout d'un redirect de l'url www.maisondelautisme.gouv.fr vers maisondelautisme.gouv.fr
Closes #x
> fix(prod): Add www redirect

- apps/strapi/src/api/fiche-pratique/content-types/fiche-pratique/lifecycles.ts
- apps/strapi/src/bootstrap/dev/create-admin.ts
- apps/strapi/src/bootstrap/dev/seed-db.ts
- apps/strapi/src/bootstrap/meilisearch/seed-pages.ts
- apps/strapi/src/commands/schemas/schema.js
- apps/strapi/src/extensions/meilisearch/strapi-server.ts
- apps/web/src/app/(main)/healthz/page.tsx
- apps/web/src/app/(main)/layout.tsx
- apps/web/src/app/(main)/mon-parcours/[slug]/page.tsx
- apps/web/src/app/(technical)/layout.tsx
- apps/web/src/app/(technical)/maintenance/page.tsx
- apps/web/src/components/base/FormGroupSelect.tsx
- apps/web/src/components/base/client/BreadcrumbDynamic.tsx
- apps/web/src/components/base/client/Header.module.css
- apps/web/src/components/base/client/Header.tsx
- apps/web/src/components/home/Article.tsx
- apps/web/src/components/utils/Markdown.tsx
- apps/web/src/design-system/base/client/ConsentBanner.tsx
- apps/web/src/design-system/hooks/useCollapse.tsx
- apps/web/src/design-system/utils/ButtonStyles.ts
- apps/web/src/pages/api/mail.ts
- apps/web/src/pages/api/strapi/webhook.ts
- apps/web/src/services/strapi.ts
Fixes #285
Cette PR traite les bugs et code smells remontés par Sonar
> fix(sonar): easy bugs & code smells

- apps/web/src/app/(main)/accessibilite/page.tsx
- apps/web/src/app/(main)/annuaire/page.tsx
- apps/web/src/app/(main)/fiches-pratiques/[slug]/page.tsx
- apps/web/src/app/(main)/fiches-pratiques/page.tsx
- apps/web/src/app/(main)/glossaire/page.tsx
- apps/web/src/app/(main)/healthz/page.tsx
- apps/web/src/app/(main)/je-donne-mon-avis/page.tsx
- apps/web/src/app/(main)/la-maison-de-l-autisme/page.tsx
- apps/web/src/app/(main)/mentions-legales/page.tsx
- apps/web/src/app/(main)/mes-aides/page.tsx
- apps/web/src/app/(main)/modeles-de-courrier/page.tsx
- apps/web/src/app/(main)/mon-diagnostic/page.tsx
- apps/web/src/app/(main)/mon-parcours/[slug]/page.tsx
- apps/web/src/app/(main)/mon-parcours/page.tsx
- apps/web/src/app/(main)/page.tsx
- apps/web/src/app/(main)/parcours/[slug]/page.tsx
- apps/web/src/app/(main)/parcours/page.tsx
- apps/web/src/app/(main)/plan-du-site/page.tsx
- apps/web/src/app/(main)/politique-de-confidentialite/page.tsx
- apps/web/src/app/(main)/recherche/page.tsx
Sonar considère les pages next comme du code dupliqué... Ce n'est pas vraiment le cas
> chore(sonar): Make this b****** understand that it is not duplication

- apps/strapi/config/sync/core-store.plugin_content_manager_configuration_components##common.articles.json
- apps/strapi/src/components/common/articles.json
- apps/web/src/components/home/Carousel.tsx
- apps/web/src/styles/global.css
Closes #303 
Cette PR ajoute des styles au carousel et configure le back office
> chore(carousel): various improvements

- apps/strapi/package.json
- apps/strapi/src/admin/app.tsx
- apps/strapi/src/admin/extensions/meilisearch/Page.tsx
- apps/strapi/src/admin/extensions/meilisearch/components/MeilisearchSettings.tsx
- apps/strapi/src/admin/extensions/meilisearch/hooks/useAlert.ts
- apps/strapi/src/admin/extensions/meilisearch/hooks/useSettings.ts
- apps/strapi/src/admin/extensions/meilisearch/settings.tsx
- apps/strapi/src/admin/global.d.ts
- apps/strapi/src/admin/tsconfig.json
- apps/strapi/src/bootstrap/index.ts
- apps/strapi/src/bootstrap/meilisearch/configure-index.ts
- apps/strapi/src/extensions/meilisearch/content-types/index.ts
- apps/strapi/src/extensions/meilisearch/content-types/meilisearch-index/index.ts
- apps/strapi/src/extensions/meilisearch/content-types/meilisearch-index/schema.json
- apps/strapi/src/extensions/meilisearch/controllers/index-settings.ts
- apps/strapi/src/extensions/meilisearch/controllers/search.ts
- apps/strapi/src/extensions/meilisearch/services/index-settings.ts
- apps/strapi/src/extensions/meilisearch/strapi-server.ts
- package.json
- packages/strapi-types/strapi.d.ts
- yarn.lock
Closes #239
Cette PR ajoute une page dans l'admin afin de configurer meilisearch
> feat(meilisearch): search config

- apps/web/src/app/(main)/mon-diagnostic/DiagSteps.tsx
- apps/web/src/app/(main)/mon-diagnostic/diagnosticStore.ts
- apps/web/src/app/(main)/mon-diagnostic/page.tsx
- apps/web/src/services/strapi.ts
- packages/strapi-plugin-mda/src/admin/src/components/MdaDiagnostic.tsx
- packages/strapi-types/index.d.ts
- Closes #125 
Cette PR bascule la page de diagnostic sur la nouvelle API
> feat(diagnostic-v2): front

- .kontinuous/env/prod/values.yaml
- Closes #334 
Cette PR augmente les limites m'emoire en production
> fix(prod): Increase memory limits

- apps/web/package.json
- packages/eslint-config/package.json
- yarn.lock
Cette PR revert la version de next en 13.3.4 qui était celle d'avant 9 mai où nous avons commencé à constater le problème.
> fix(memory): revert next in v13.3.4

- README.md
- apps/strapi/README.md
- apps/web/README.md
- package.json
- packages/strapi-plugin-mda/README.md
- Closes #120 
Cette PR met à jour la documentation du projet sur 3 axes
- Présentation générale + architecture
- Ajout des services docker manquants
- Amélioration de l'existant
> docs(README): update

- apps/web/package.json
- apps/web/src/app/(main)/accessibilite/page.tsx
- apps/web/src/app/(main)/annuaire/page.tsx
- apps/web/src/app/(main)/fiches-pratiques/[slug]/page.tsx
- apps/web/src/app/(main)/je-donne-mon-avis/page.tsx
- apps/web/src/app/(main)/la-maison-de-l-autisme/page.tsx
- apps/web/src/app/(main)/mentions-legales/page.tsx
- apps/web/src/app/(main)/mes-aides/page.tsx
- apps/web/src/app/(main)/modeles-de-courrier/page.tsx
- apps/web/src/app/(main)/mon-diagnostic/page.tsx
- apps/web/src/app/(main)/mon-parcours/[slug]/page.tsx
- apps/web/src/app/(main)/page.tsx
- apps/web/src/app/(main)/parcours/[slug]/page.tsx
- apps/web/src/app/(main)/plan-du-site/page.tsx
- apps/web/src/app/(main)/politique-de-confidentialite/page.tsx
- apps/web/src/components/utils/JsonLd.tsx
- apps/web/src/services/metadata.ts
- yarn.lock
- Closes #314
- Ajoute les dates de publication du contenu strapi aux metas opengraph
- Ajoute les scripts json-ld là où c'est nécessaire
> feat(seo): Add dates

- apps/web/src/app/(main)/la-maison-de-l-autisme/page.tsx
Autorise les liens dans les descriptions des évènements
> fix(events): allow links in description

- apps/web/src/app/(main)/fiches-pratiques/page.tsx
- apps/web/src/app/(main)/la-maison-de-l-autisme/page.tsx
Ajout du bloc glossaire dans fiches pratiques
> fix: ajout bloc glossaire dans fiches pratiques

- apps/strapi/src/utils/seed/menu.json
- apps/web/src/app/(main)/evenements/page.tsx
- apps/web/src/app/(main)/page.tsx
- Ajout d'une page dédiée aux évènements
- Ajout un lien depuis la home + menu
> feat: dedicated events page

- apps/web/src/components/home/Carousel.tsx
> fix: cosmetics fix #361 fix #363

- apps/web/src/styles/global.css
> fix(web): fix buttonGroups list-style-type fix #362

- apps/web/src/app/(main)/evenements/page.tsx
make it possible to use multiple links in events
> fix(events): disable isEnlargeLink

- apps/web/src/app/(main)/evenements/Tabs.tsx
- apps/web/src/app/(main)/evenements/page.tsx
> fix: events tabs fix #359

- apps/web/src/app/(main)/evenements/page.tsx
- apps/web/src/services/strapi.ts
order les events par date de fin desc
> fix(events): sort by date desc

- apps/strapi/config/plugins.ts
- apps/web/sentry.client.config.ts
- apps/web/sentry.edge.config.ts
- apps/web/sentry.server.config.ts
Reduce sentry performance sampleRate
> fix(sentry): reduce tracesSampleRate
